### ISSUE TITLE
Allow case-sensitive checking

### ISSUE THREAD

**Issue by stucox** [OnroerendErfgoed/language-tags#13]
Checking is currently case-insensitive:

```python
>>> tags.check('en-us')
True
```

BCP 47 doesn’t demand case sensitivity, so I agree case-insensitive should be default — but it recommends that the correct case should be used where possible (e.g. `en-US` rather than `en-us`).

My use case is verifying my own API’s output — so I want to be as strict as possible with this output.

Could an option be added to allow case-sensitive checking (`False` by default)?

```python
>>> tags.check('en-us', case=True)
False
>>> tags.check('en-US', case=True)
True
>>> tags.check('en-us', case=False)
True
>>> tags.check('en-us')
True
```

**Comment by cahytinne** [comment]
You can use the `tags.tag(input_value).format` property to check if the tag has the correct format.

For example:

```python
from language_tags import tags

input_value = 'en-us'
if tags.check(input_value):
    print('"{0}" is valid'.format(input_value))
    if tags.tag(input_value).format != input_value:
        print('The correct format of "{0}" is "{1}"'.format(input_value, tags.tag(input_value).format))
else:
    print('"{0}" is not valid'.format(input_value))
```

**Comment by stucox** [comment]
Aha this is great, thanks.
