### ISSUE TITLE
Library accepts some invalid tags as valid

### ISSUE THREAD

**Issue by jsommers** [OnroerendErfgoed/language-tags#17]
Hello,

Some tags can be accepted as valid, but should be invalid by your language-tags library.  An example (also given in the project changelog) is 'en-mt-arab'.  This tag is invalid according to BCP 47 (it should rather be en-Arab-MT, if in canonical form), but language-tags accepts it as valid.  The primary problem is that the grammar given in BCP 47 is not adhered to either in this library or in the javascript "ancestor" (at least as far as I can tell; I didn't look deeply at it because I'm interested in a Python implementation).  It looks like the parsing is done in a much more ad-hoc way rather than by the grammar.  You may wish not to modify until or unless the upstream Javascript version is changed, but I think it is important to note that the library currently accepts invalid tags as valid.

A validator that correctly parses the above invalid example can be found at http://schneegans.de/lv/; it indicates that it is invalid, but a switch to en-arab-mt is correctly accepted.

**Comment by koenedaele** [comment]
Thanks. We created this a quick port of the JS version, so we didn't check all the parsing rules.

We'll have to see how much room we have at the moment to make far-fetching changes. Feel to free to make a suggestion on how to implement this or get in touch with @cahytinne who is the lead on this project.

I've noticed there's also https://github.com/LuminosoInsight/langcodes in Python. I haven't checked it intensively, but maybe that library gets it right? It also seems so do a lot our library doesn't, so I might be a better fit for you anyway?

**Comment by jsommers** [comment]
Thanks for the tip on the other repo!  Yes, I think it's a better fit anyway.  Yours was the top hit on pypi so that's where I started :-)  

I'm happy if you close this issue.  It's (obviously) up to you whether you'd want to diverge from the JS version in any significant way, so such far-reaching changes may simply be out of scope for this project.
