### ISSUE TITLE
language tag 'aa' is detected as invalid

### ISSUE THREAD

**Issue by WangJiannan** [OnroerendErfgoed/language-tags#27]
```python
>>> from language_tags import tags
>>> tags.check('aa')
False
>>> tags.tag('aa').errors[0].message
"Missing language tag in 'aa'."
```

However, I find 'aa' is just the first subtag in [language-subtag-registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry). And online [BCP 47 Validator](http://schneegans.de/lv/) tells that 'aa' is valid and well-formed language tag.

**Comment by WangJiannan** [comment]
I had sent pull request to fix this issue: https://github.com/OnroerendErfgoed/language-tags/pull/28
 (The CI failure is due to coverage decreased which results from code deletion)

**Comment by cahytinne** [comment]
Thank you. The bug only appeared with the language tag 'aa' because it had a index value of 0.
I will make a new release with the fix.
