### ISSUE TITLE
Differences Between Versions

### ISSUE THREAD

**Issue by vladipus** [OnroerendErfgoed/language-tags#6]
Why does the version at GitHub differs from that in the registry: https://pypi.python.org/pypi/language-tags ?

**Comment by cahytinne** [comment]
The version on GitHub was missing one last commit https://github.com/OnroerendErfgoed/language-tags/commit/ebf21d7d8d599022580d22b326a3a163d02a5455 . I pushed It, so there shouldn't be any difference anymore. The commit only included a version number change and a history log, so no changes in the functionality of the code were made.

The download files in the releases on GitHub an PyPi remained the same. The was no difference between them. 

Thanks for reporting this.
